### ISSUE TITLE
xmbindings cheat sheet font missing

### ISSUE THREAD

**Issue by mzrinsky** [xmonad/xmonad-web#34]
I noticed when doing some work on the xmbindings cheat sheet recently, that the font referenced in the svg (which also appeared in the original png) was missing from my system.

There are actually a few fonts referenced in the svg, but the main typewriter style font which was missing is `TlwgTypewriter`.
It seems like the full list of fonts from the svg are..
`DejaVu Sans`, `DejaVu Sans Mono`, `Bitstream Vera Sans Mono`, `TlwgTypewriter`, and `Monospace`.

I downloaded a copy of `TlwgTypewriter` to do my edits, but thought it would be better to either link to the correct font, which seems like it is currently maintained on GitHub, https://github.com/tlwg/fonts-tlwg, with the current release at https://github.com/tlwg/fonts-tlwg/releases/tag/v0.7.2

I wanted to just mention it here to at least start a discussion about it.  I am not really sure what the preferred fix would be, but thought it was worth bringing up at least.

Thanks for your time!

**Comment by slotThe** [comment]
Well, I guess the _real_ fix would be to not use five different fonts for such a small image.  I'm very oblivious to stuff like this, but when looking at it I can see two different fonts at the most

**Comment by mzrinsky** [comment]
I just grepped the svg for `font-family` and put the list I came up with here. I did not see the point in bringing up an issue about a missing font, without at least mentioning all the font names being used. 
Additionally I did not want to make a judgement call on anything since I had literally looked at the svg once.

IMHO it seems like using the other fonts was probably just a mistake?
The `Monospace` font-family lines appear in `style` tags in `text` blocks, and then are overridden by `style` tags in `tspan` blocks to be `DejaVu Sans Mono`, so that can be cleaned up and removed without changing anything visual about the image.

Looking through the svg more (they are XML) it seems `Bitstream Vera Sans Mono` is only really being used for the letter `J`, it is mentioned in some other `style` tags, but those seem to be paths, so that can be changed to be `DejaVu Sans Mono` like the rest, and again was probably just a mistake.

`DejaVu Sans` seems to be used for a few of the top lines of text like `programs`, `xinerama` so those can probably be changed to use `DejaVu Sans Mono` as well, which seems to be the font used on all the letters on the key map.

To sum up..
My suggestion after looking closer at the svg, would be to remove all the `Monospace` references and change anything that is not `TlwgTypewriter` to `DejaVu Sans Mono`.

I personally feel it is worth maintaining the second font in the image, `TlwgTypewriter`, even if the only reason is that it was in the original image.
But that is just my personal opinion.


That would leave one final question, which is what to do about `TlwgTypewriter` in the first place?

If you agree it should be kept in the image, it should probably be mentioned or linked to somehow so in the future people know it should be used, and know where to download it from.

If not then it should just get replaced with `DejaVu Sans Mono` so there is one less thing to maintain.

Either way I feel like something should be done about it.
Is there some sort of style guide for the xmonad-web project where things like that are documented?

**Comment by slotThe** [comment]
[[ Sorry about the late reply, I quite literally forgot this existed ]]

> IMHO it seems like using the other fonts was probably just a mistake?

That may be the case yes.  At this point, I think the origins of the
.svg are lost in time.

> My suggestion after looking closer at the svg, would be to remove all
> the `Monospace` references and change anything that is not
> `TlwgTypewriter` to `DejaVu Sans Mono`.
> 
> I personally feel it is worth maintaining the second font in the
> image, `TlwgTypewriter`, even if the only reason is that it was in the
> original image.
> But that is just my personal opinion.

That's fair enough; if you think it's worth doing that then I personally
have no qualms about keeping `TlwgTypewriter` and just linking to it.
We can always change it when the burden of maintenance becomes too much,
but since the cheatsheet doesn't change all that often I think it'll be
fine.

> Is there some sort of style guide for the xmonad-web project where
> things like that are documented?

There is not, the website was relatively dormant up until a few
weeks/months ago.

**Comment by mzrinsky** [comment]
> [[ Sorry about the late reply, I quite literally forgot this existed ]]

This is certainly not a critical issue or anything so it is really not a problem.

> That's fair enough; if you think it's worth doing that then I personally
> have no qualms about keeping `TlwgTypewriter` and just linking to it.
> We can always change it when the burden of maintenance becomes too much,
> but since the cheatsheet doesn't change all that often I think it'll be
> fine.

Would just adding a Readme.md to the cheat folder make sense then and just linking to it from there?
I don't really want to clutter the main readme with such a small detail, but I honestly don't know where the best place to put a link to it would be.

Thank you for your input on this.

**Comment by slotThe** [comment]
> Would just adding a Readme.md to the cheat folder make sense then and just linking to it from there?
> I don't really want to clutter the main readme with such a small detail, but I honestly don't know where the best place to put a link to it would be.

I think adding a readme file to the cheatsheet directory sounds like a good idea!  People making changes would surely run across it that way.

You're probably right with regards to the main readme; the cheatsheet does not get updated very often (changing the default keybindings is, at this point, not really on the cards anymore) and so most people who'd like to work on the website probably won't care too much about this.

> Thank you for your input on this.

Thank _you_ for caring
