### ISSUE TITLE
Beautify Xmonad Official Website

### ISSUE THREAD

**Issue by wisn** [xmonad/xmonad-web#5]
Is there any plan to beautify Xmonad official website? I do love to help in this part. What is your opinion, @pjones?

The Xmonad complete documentation will be looks nice as well.

**Comment by tsier** [comment]
Hi @wisn I forked your repo and tried your hakyll setup, which worked really well. I got a bit carried away and also started redesigning and restructuring.
@pjones I think working with hakyll and markdown is quite convenient.  It's also easy to integrate some HTML which makes the styling possible.   

I deployed the result of my design experiment to my github page [link to demo](https://tsier.github.io/xmonad-web/index.html)
The design is based on the official Haskell page and has now a new layout and is responsive.

Please let me know wheter you think this is going in the right direction. I also think it would make sense to change the structure of the site a bit more to make it easier to get started.

**Comment by wisn** [comment]
That was cool @tsier. I'm lost in this issue. It would be good if you take over this.

**Comment by smolck** [comment]
@tsier I think your re-design looks really good; it's quite a nice refresh! Have you stopped working on this? I would love to get this moving again!

**Comment by TheMC47** [comment]
Another friendly ping for @wisn and @tsier: it's awesome that you took initiative on this. Do you want to keep working on it?

**Comment by wisn** [comment]
Hi @TheMC47, I think @tsier work is better than me so I'm giving this issue to him/her. If you by any chance want to work on this, better to talk to @tsier.

**Comment by TheMC47** [comment]
@wisn @tsier thank you both for starting to work on this, I've taken your work as a basis for #19

**Comment by TheMC47** [comment]
Closed by #20
