### ISSUE TITLE
Linux Distro Missing [void]

### ISSUE THREAD

**Issue by marcelfoss** [xmonad/xmonad-web#57]
found in the repo for musl and glibc for amd64

--> https://voidlinux.org/packages/?arch=x86_64&q=xmonad

**Comment by slotThe** [comment]
The packages were removed in [this PR](https://github.com/void-linux/void-packages/pull/33749) because installing system libraries with stack is a bad idea and Void builds Haskell things entirely with stack.

**Comment by marcelfoss** [comment]
@slotThe I see! Nevertheless they are still online, but none of your concern. I build it using stack without any problems perhaps it is somehow possible to build it for void.

**Comment by slotThe** [comment]
On Sun, Mar 06 2022 12:09, Marcel wrote:
> @slotThe I see! Nevertheless they are still online, but none of your
> concern.

They are, but they are also in removed-packages already[1], which means
that every time you update xbps will automatically remove them.

> I build it using stack without any problems perhaps it is somehow
> possible to build it for void.

Me too, actually! :)

[1]: https://github.com/void-linux/void-packages/blob/master/srcpkgs/removed-packages/template#L389-L390

**Comment by marcelfoss** [comment]
now I understand why I never was able to see xmonad w/ lightdm ;) I already thought I was too stupid :D thanks!
Perhaps it might make sense to put the dependencies for void on top to those other Distributions like Fedora, Arch, Debian etc which anyway resolve them with their pkg-managers

**Comment by slotThe** [comment]
On Sun, Mar 06 2022 12:34, Marcel wrote:
> Perhaps it might make sense to put the dependencies for void on top to
> those other Distributions like Fedora, Arch, Debian etc which anyway
> resolve them with their pkg-managers

Sure, that sounds like a plan; do you fancy contributing this?

**Comment by marcelfoss** [comment]
@slotThe here we go ;)

those are all depdencies after a fresh install with the basic package:

`pkg-config gcc xz make ncurses-libtinfo-libs ncurses-libtinfo-devel stack git xorg libXft-devel libXScrnSaver-devel libX11-devel libXft-devel libXinerama-devel libXrandr-devel`

install:
`# xbps-install []`

**Comment by slotThe** [comment]
Done in https://github.com/xmonad/xmonad/commit/89ea1356c176f3710023c6a324b97c5426530b61; thanks!
