### ISSUE TITLE
Creates a Special Branch for Hakyll Application

### ISSUE THREAD

**Issue by wisn** [xmonad/xmonad-web#6]
Currently, I'm trying to restructuring the `xmonad-web` in [this repository](https://github.com/wisn/xmonad-web/tree/rebuild-xmonad-web). I'm created a new branch for the Hakyll application separately form the `gh-pages` branch. So, contributor will contributing on the Hakyll branch instead of the `gh-pages` directly. Contributor will send the PR to the Hakyll branch. Then, we may deploy the commits with `xmonad-web deploy` command. Here is the `deployCommand`:

```
cp -r app/html/ ../xmonad-html/ && git checkout gh-pages && cp -rf ../xmonad-html/* . && rm -r ../xmonad-html/ && git status
```

Yes, the deploy command will bring us to the `gh-pages` branch and replace all the changes. So, the `gh-pages` will contain the web contents only. Any advice?

**Comment by TheMC47** [comment]
See #20
